docs_dir: docs/book
site_dir: docs/html
nav:
  - Home: index.md
site_name: oneplace-templates
site_description: "onePlace Template Collection"
repo_url: 'https://github.com/OnePlc/PLC_X_Templates'
theme: bootstrap4
extra:
  project: onePlc