<?php
$sCardClassFinal = (!isset($sCardClass)) ? 'col-md-12' : $sCardClass;
?>
<div class="<?=$sCardClassFinal?>">
    <div class="card">
        <div class="card-header">
            <h1 class="card-title"><?=$sCardTitle?></h1>
        </div>
        <div class="card-body">
            <?=$sCardBody?>
        </div>
        <div class="card-footer">
            <?=$sCardFooter?>
        </div>
    </div>
</div>