<?php
/**
 * basic.phtml - Basic Card
 *
 * Main Template file for Basic Bootstrap Card
 *
 * @category Template
 * @package Template
 * @author Verein onePlace
 * @copyright (C) 2021  Verein onePlace <admin@1plc.ch>
 * @license https://opensource.org/licenses/BSD-3-Clause
 * @version 1.0.0
 * @since 1.0.0
 */
$sCardClassFinal = (!isset($sCardClass)) ? 'col-md-12' : $sCardClass;
?>
<div class="<?=$sCardClassFinal?>">
    <div class="card">
        <div class="card-header">
            <h1 class="card-title"><?=$sCardTitle?></h1>
        </div>
        <div class="card-body">
            <?=$sCardBody?>
        </div>
        <div class="card-footer">
            <?=$sCardFooter?>
        </div>
    </div>
</div>